[package]
name = "main"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v0.87.4", directory = "noir-projects/aztec-nr/aztec" }
